initial commit
logstash-plugins/logstash-input-dead_letter_queue pull request #1
Opened 2017-02-01 01:50 UTC by talevy

2017-03-29 18:00 UTC, suyograo requested changes

2017-03-29 18:00 UTC, suyograo commented on lib/logstash/inputs/dlq.rb
> +  config_name 'dlq'
I think we need to be consistent. Elsewhere, we've used the full dead_letter_queue (in core config) and here its DLQ. dead_letter_queue is long, but it's self-explanatory to users who are not familiar with this terminology.

2017-03-29 18:00 UTC, suyograo commented on lib/logstash/inputs/dlq.rb
> +  config :sincedb, :validate => :string, :required => false
By default this should be in `path.data/plugins/inputs/dead_letter_queue/`. That's what file input uses. Also rename to sincedb_path to match file input.

2017-03-29 18:00 UTC, suyograo commented on lib/logstash/inputs/dlq.rb
> +  config :timestamp, :validate => :string, :required => false
Maybe call it `from_timestamp` or `start_timestamp`. Just a `timestamp` may not be very obvious.

2017-04-04 22:14 UTC, talevy commented
Merging to Close the loop on this. Work still needs to be done before publishing. This is a good start for iterative improvements until version 1.0

2017-04-04 22:14 UTC, merged