Fix broken reference to DeadLetterQueue*Manager
logstash-plugins/logstash-input-dead_letter_queue pull request #3
Opened 2017-05-31 20:14 UTC by robbavey

Change test to refer to DeadLetterQueueWriter instead of DeadLetterQueueWriteManager
Remove unnecessary (and broken) reference to DeadLetterQueueReadManager
Change variable and access to refer to ...Reader, instead of ...ReadManager

2017-05-31 20:24 UTC, talevy requested changes
left a quick note regarding the CHANGELOG. LGTM otherwise

2017-05-31 20:24 UTC, talevy commented on CHANGELOG.md
> +## 1.0.2
we usually place the versions in the reverse order

example: https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/master/CHANGELOG.md

2017-06-05 16:29 UTC, suyograo commented
@robbavey should we merge this, since you're fixing the tests in #4 ?

2017-06-05 16:47 UTC, robbavey commented
Sure, I think I can go ahead - Tal's objection was pretty cosmetic

2017-06-05 16:55 UTC, talevy approved these changes

2017-06-05 18:04 UTC, merged