WiP
logstash-plugins/logstash-input-dead_letter_queue pull request #35
Opened 2022-02-24 08:52 UTC by kares

...

2022-02-24 17:01 UTC, andsel requested changes
Left some concerns here and there, generally is good, many are matter of test. But the naming of the getter method name deserve some love :-)

2022-02-24 17:01 UTC, andsel commented on src/main/java/org/logstash/input/DeadLetterQueueInputPlugin.java
> +            // NOTE: avoid creating DLQReader is these fail so that on plugin restarts the inotify limit is not decremented
```suggestion
            // NOTE: avoid creating DLQReader if these fail so that on plugin restarts the inotify limit is not decremented
```

2022-02-24 17:01 UTC, andsel commented on src/main/java/org/logstash/input/DeadLetterQueueInputPlugin.java
> +    private synchronized DeadLetterQueueReader getQueueReader() throws IOException {
The name is little misleading, I would rename it something like `getOrCreateQueueReader` or maybe `lazyInitQueueReader`, something that exposes that the queueReader is created here, that the status of the instance is changed by this call.

2022-02-24 17:01 UTC, andsel commented on src/test/java/org/logstash/input/DeadLetterQueueInputPluginTests.java
> +            // should not throw java.io.IOException "User limit of inotify instances reached or too many open files"
I understand that any exception here generated a test break, but do you think we could capture that this failure is something we are guarding against? This IOException is different from a no disk space left, it happens it mean the code doesn't fix the issue. 
I just wonder for your opinion.

2022-02-24 17:01 UTC, andsel commented on src/main/java/org/logstash/input/DeadLetterQueueInputPlugin.java
> +            if (queueReader != null) queueReader.close();
I'm not a fan of single line ifs, but maybe this is just a question of personal taste

2022-02-24 17:01 UTC, andsel commented on src/test/java/org/logstash/input/DeadLetterQueueInputPluginTests.java
> +    public void testIT() throws Exception {
`test` wasn't a good name, maybe some more descriptive name, like 
```suggestion
    public void testHappyPath() throws Exception {
```

or `testNormalExecution` ?

2022-02-24 17:21 UTC, kares commented on src/test/java/org/logstash/input/DeadLetterQueueInputPluginTests.java
> +    public void testIT() throws Exception {
it's kind of an "integration" test but HappyPath sounds good as well :wink:

2022-02-24 17:22 UTC, kares commented on src/main/java/org/logstash/input/DeadLetterQueueInputPlugin.java
> +    private synchronized DeadLetterQueueReader getQueueReader() throws IOException {
good call and I've been thinking about (as I too a method that existed before) that just forgot ...

2022-03-01 09:18 UTC, andsel approved these changes
LGTM,
left only a nitpick, so that the readability of the test should be increased, feel free to skip.

2022-03-01 09:18 UTC, andsel commented on src/test/java/org/logstash/input/DeadLetterQueueInputPluginTests.java
> +                assertFalse("User limit of inotify instances reached or too many open files".equals(e.getMessage()));
```suggestion
                Assert.assertNotEquals("User limit of inotify instances reached or too many open files", e.getMessage());
```

2022-03-01 09:18 UTC, andsel commented on src/test/java/org/logstash/input/DeadLetterQueueInputPluginTests.java
>  import org.junit.Before;
```suggestion
import org.junit.Assert;
import org.junit.Before;
```

2022-03-01 12:26 UTC, merged