Fix NPE when the plugin closes
logstash-plugins/logstash-input-dead_letter_queue pull request #53
Opened 2024-08-29 13:21 UTC by kaisecheng

Fix NPE when the plugin closes with the following conditions
- dead letter queue directory has never had a available segment
- commit_offsets => true
- start_timestamp is not specified
- sincedb_path => "/path/to/sincedb"

This commit catches NullPointerException when updating SinceDB before shutdown

Fix: https://github.com/elastic/logstash/issues/16404

---

To test this PR 
```
# dlq.conf
input {
    dead_letter_queue {
        path => "/tmp/logstash/data/dead_letter_queue"  # /tmp/logstash/data/dead_letter_queue/pipe1 should be empty folder
        sincedb_path => "/path/to/sincedb" # a valid non empty sincedb
        commit_offsets => true
        pipeline_id => "pipe1"
    }
}
output {
    stdout {  }
}
```
- Run `bin/logstash -f dlq.conf`
- After pipeline started, shutdown logstash
- You can see NO error

2024-09-02 15:06 UTC, andsel requested changes
The PR works as declared protecting against empty DLQ paths.
Left some suggestions on better naming.

2024-09-02 15:06 UTC, andsel commented on src/test/java/org/logstash/input/DeadLetterQueueInputPluginTests.java
> +    }
```suggestion
    }

```

2024-09-02 15:06 UTC, andsel commented on src/main/java/org/logstash/input/SinceDB.java
> +    static SinceDB mayUpdate(SinceDB oldSinceDb, DeadLetterQueueReader reader) {
```suggestion
    static SinceDB tryUpdate(SinceDB oldSinceDb, DeadLetterQueueReader reader) {
```

2024-09-02 15:06 UTC, andsel commented on src/main/java/org/logstash/input/DeadLetterQueueInputPlugin.java
> +            sinceDb = SinceDB.mayUpdate(sinceDb, queueReader);
```suggestion
            sinceDb = SinceDB.tryUpdate(sinceDb, queueReader);
```

2024-09-02 15:06 UTC, andsel commented on src/main/java/org/logstash/input/SinceDB.java
> +     * @return new instance of SinceDB or UnassignedDB
```suggestion
     *
     * @param oldSinceDb of SinceDB to update
     * @param reader the reader that needs to be queried.
     * @return new instance of SinceDB or UnassignedDB if the reader doesn't point to an existing segment.
```

2024-09-02 15:56 UTC, kaisecheng commented
@andsel thanks for the review and suggestion. 

I am thinking if [readerHasState](https://github.com/logstash-plugins/logstash-input-dead_letter_queue/blob/v2.0.0/src/main/java/org/logstash/input/DeadLetterQueueInputPlugin.java#L126) should set to `false` when `queueReader.setCurrentReaderAndPosition()` find no segment, hence, [SinceDB](https://github.com/logstash-plugins/logstash-input-dead_letter_queue/blob/v2.0.0/src/main/java/org/logstash/input/DeadLetterQueueInputPlugin.java#L157-L160) no need to update when close. The issue seems to be misalignment of the state rather than missing try-catch. WDYT?

2024-09-03 08:51 UTC, andsel commented
@kaisecheng I agree with you, if the reader doesn't have a link to a valid segment (`RecordIOReader currentReader`), it  should be considered as without state to store.
As in the actual form of the PR, we are treating the symptom and not the cause, however in general I was wondering if the information of such state has to be contained in the DLQ input plugin or should be part of the `DeadLetterQueueReader` itself.

We can proceed in two steps:
- treat the symptom with this PR, that would fix actual installations (LS >= 8.4)
- fix the cause, so work on the LS core part

Fixing the cause would open a big question in my opinion. That would require a method (`DeadLetterQueueReader.setCurrentReaderAndPosition`) to return a value, this is a change that should be binary compatible, so it should work also with previous version of the plugin. Once we have a release of LS with that change we can proceed in updating then the DLQ input plugin. 
Having the DLQ input plugin as part of the LS core would greatly simplify the release process, should we consider moving it?

2024-09-03 14:36 UTC, kaisecheng commented
Agree that we can proceed with this PR first and fix the state in core later.

Putting the DeadLetterQueueInputPlugin to core or plugin is about where to put the line between two. I think the line always exists, as the register(), close() and run() need to interact with the plugin. We need a better interface and move all `DeadLetterQueueReader` related state and SinceDB to core. So, when ruby plugin do close(), it only call the interface close without considering `queueReader`, `commitOffsets`, `readerHasState` and `sinceDb`

2024-09-04 13:27 UTC, jsvd commented
Fixing this in core touches on https://github.com/elastic/logstash/issues/8682. Plugins like this one, file input, jdbc and es input should be able to leverage storage primitives to store plugin state.

2024-09-04 17:05 UTC, andsel approved these changes
LGTM

2024-09-04 23:51 UTC, merged